name = "MockHTTPServer"
uuid = "9847a9a8-26d8-4fdf-be5f-03741db45a13"
authors = ["Tanmay Mohapatra <tanmaykm@gmail.com>"]
version = "0.1.0"

[deps]
HTTP = "cd3eb016-35fb-5094-929b-558a96fad6f3"
Sockets = "6462fe0b-24de-5631-8697-dd941f90decc"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]

[compat]
julia = "1.6"
HTTP = "1"
